version: 5.4.0-{build}

image: Visual Studio 2017

configuration: Release
platform: Any CPU

before_build:
  - dotnet restore

build_script:
  - dotnet build src\LaunchDarkly.Client\LaunchDarkly.Client.csproj

after_build:
  - dotnet pack src\LaunchDarkly.Client\LaunchDarkly.Client.csproj

test_script:
  - dotnet test test\LaunchDarkly.Tests\LaunchDarkly.Tests.csproj

artifacts:
  - path: 'src\LaunchDarkly.Client\bin\**\*.nupkg'
    name: Nuget