version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2-sdk-jessie
    steps:
      - checkout
      - run:
          name: install packages
          command: |
            sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893;
            aws s3 cp s3://launchdarkly-pastebin/ci/dotnet/LaunchDarkly.snk LaunchDarkly.snk
      - run: dotnet restore
      - run: dotnet build src/LaunchDarkly.Client -f netstandard1.4
      - run: dotnet build src/LaunchDarkly.Client -f netstandard1.6
      - run: dotnet build src/LaunchDarkly.Client -f netstandard2.0
      - run: dotnet test test/LaunchDarkly.Tests/LaunchDarkly.Tests.csproj
